title: Ryan Arias Delafosse
logo: "assets/images/Headshot.png"

description: |
  <p><strong>Data Scientist @ World Bank</strong></p>
  <p>Data scientist focused on humanitarian aid and international development.</p>

theme: jekyll-theme-minimal
show_downloads: false

url: "https://rydela.github.io"
baseurl: ""

email: r.arias.delafosse@gmail.com
role: Data Scientist @ World Bank
location: Paris, France

social:
  github: "https://github.com/Rydela"
  linkedin: "https://www.linkedin.com/in/rydelafosse/"

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

exclude:
  - scripts
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .bundle
  - .home
  - .local-gems
  - .vendor
